matrix:
  platform:
    - linux/amd64
    - linux/arm64

labels:
  platform: ${platform}

when:
  event: tag

depends_on:
  - build

variables:
  .ssh_setup_start_agent: &ssh_setup_start_agent eval $(ssh-agent -s)
  .ssh_setup_import_key: &ssh_setup_import_key echo "$${CI_PRIVATE_SSH_KEY}" | ssh-add -
  .ssh_setup_configure: &ssh_setup_configure mkdir -p ~/.ssh && echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
  .install_ssh: &install_ssh apk update && apk add openssh-client

steps:
  prepare-env:
    image: alpine:latest
    commands:
      - apk update && apk add git
      - chmod +x ./scripts/*.sh
      - ./scripts/prepare_env.sh

  prepare-storage:
    image: alpine:latest
    environment:
      CI_SSH_HOST:
        from_secret: storage_ssh_host
      CI_SSH_PORT:
        from_secret: storage_ssh_port
      CI_SSH_USER:
        from_secret: storage_ssh_user
      CI_PRIVATE_SSH_KEY:
        from_secret: storage_ssh_key
      CI_STORAGE_PREFIX:
        from_secret: storage_directory_prefix
    commands:
      - export $(grep -v '^#' .env | xargs)
      - *install_ssh
      - *ssh_setup_start_agent
      - *ssh_setup_import_key
      - *ssh_setup_configure
      - mkdir ./dists/
      - scp -P $${CI_SSH_PORT} "$${CI_SSH_USER}@$${CI_SSH_HOST}:$${CI_STORAGE_PREFIX}/$${CI_PRETTY_VERSION}/KSRE-linux.tar.bz2" ./dists/
    depends_on:
      - prepare-env

  build:
    image: debian:latest
    commands:
      - export $(grep -v '^#' .env | xargs)
      - apt update && apt install -y wget bzip2 file
      - ./scripts/appimage.sh
    depends_on:
      - prepare-env
      - prepare-storage

  upload-assets:
    image: alpine:latest
    environment:
      CI_SSH_HOST:
        from_secret: storage_ssh_host
      CI_SSH_PORT:
        from_secret: storage_ssh_port
      CI_SSH_USER:
        from_secret: storage_ssh_user
      CI_PRIVATE_SSH_KEY:
        from_secret: storage_ssh_key
      CI_STORAGE_PREFIX:
        from_secret: storage_directory_prefix
    commands:
      - export $(grep -v '^#' .env | xargs)
      - *install_ssh
      - *ssh_setup_start_agent
      - *ssh_setup_import_key
      - *ssh_setup_configure
      - scp -P $${CI_SSH_PORT} ./dists/*.AppImage "$${CI_SSH_USER}@$${CI_SSH_HOST}:$${CI_STORAGE_PREFIX}/$${CI_PRETTY_VERSION}/"
    depends_on:
      - prepare-env
      - prepare-storage
      - build
