name: Build

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
env:
  SDL_AUDIODRIVER: dummy
  SDL_VIDEODRIVER: dummy
  RENPY_VERSION: 8.2.3
  RENKIT_VERSION: 4.4.0
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build
        run: |
          unset ANDROID_NDK_HOME
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/kobaltcore/renkit/releases/download/v${{ env.RENKIT_VERSION }}/renkit-installer.sh | sh
          export PATH=~/.cargo/bin:$PATH
          [ ! -d ~/.renutil ] && renutil install ${{ env.RENPY_VERSION }}
          mkdir -p ~/.renutil/${{ env.RENPY_VERSION }}/rapt/project/app/
          sed -i 's#{KEYSTORE_APK}#${{ secrets.ANDROID_KEYSTORE }}#' renconstruct.toml
          sed -i 's#{KEYSTORE_ALIAS}#${{ secrets.KEYSTORE_ALIAS }}#' renconstruct.toml
          sed -i 's#{KEYSTORE_PASS}#${{ secrets.KEYSTORE_PASS }}#' renconstruct.toml
          sed -i 's#{RENPY_VERSION}#${{ env.RENPY_VERSION }}#' renconstruct.toml
          renconstruct build -c renconstruct.toml . ${{ github.workspace }}/dists/

      - name: Release binaries
        uses: svenstaro/upload-release-action@2.9.0
        with:
          file: ${{ github.workspace }}/dists/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          draft: true
          body: "This is a test."
